#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qlsv")]
	public partial class QLSVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_lop(tbl_lop instance);
    partial void Updatetbl_lop(tbl_lop instance);
    partial void Deletetbl_lop(tbl_lop instance);
    partial void Inserttbl_sinhvien(tbl_sinhvien instance);
    partial void Updatetbl_sinhvien(tbl_sinhvien instance);
    partial void Deletetbl_sinhvien(tbl_sinhvien instance);
    partial void Inserttbl_taikhoan(tbl_taikhoan instance);
    partial void Updatetbl_taikhoan(tbl_taikhoan instance);
    partial void Deletetbl_taikhoan(tbl_taikhoan instance);
    #endregion
		
		public QLSVDataContext() : 
				base(global::QLSV.Properties.Settings.Default.qlsvConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_lop> tbl_lops
		{
			get
			{
				return this.GetTable<tbl_lop>();
			}
		}
		
		public System.Data.Linq.Table<tbl_sinhvien> tbl_sinhviens
		{
			get
			{
				return this.GetTable<tbl_sinhvien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_taikhoan> tbl_taikhoans
		{
			get
			{
				return this.GetTable<tbl_taikhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lop")]
	public partial class tbl_lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _malop;
		
		private string _tenlop;
		
		private string _tengvcn;
		
		private System.Nullable<int> _siso;
		
		private EntitySet<tbl_sinhvien> _tbl_sinhviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmalopChanging(string value);
    partial void OnmalopChanged();
    partial void OntenlopChanging(string value);
    partial void OntenlopChanged();
    partial void OntengvcnChanging(string value);
    partial void OntengvcnChanged();
    partial void OnsisoChanging(System.Nullable<int> value);
    partial void OnsisoChanged();
    #endregion
		
		public tbl_lop()
		{
			this._tbl_sinhviens = new EntitySet<tbl_sinhvien>(new Action<tbl_sinhvien>(this.attach_tbl_sinhviens), new Action<tbl_sinhvien>(this.detach_tbl_sinhviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malop", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string malop
		{
			get
			{
				return this._malop;
			}
			set
			{
				if ((this._malop != value))
				{
					this.OnmalopChanging(value);
					this.SendPropertyChanging();
					this._malop = value;
					this.SendPropertyChanged("malop");
					this.OnmalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenlop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenlop
		{
			get
			{
				return this._tenlop;
			}
			set
			{
				if ((this._tenlop != value))
				{
					this.OntenlopChanging(value);
					this.SendPropertyChanging();
					this._tenlop = value;
					this.SendPropertyChanged("tenlop");
					this.OntenlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tengvcn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tengvcn
		{
			get
			{
				return this._tengvcn;
			}
			set
			{
				if ((this._tengvcn != value))
				{
					this.OntengvcnChanging(value);
					this.SendPropertyChanging();
					this._tengvcn = value;
					this.SendPropertyChanged("tengvcn");
					this.OntengvcnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siso", DbType="Int")]
		public System.Nullable<int> siso
		{
			get
			{
				return this._siso;
			}
			set
			{
				if ((this._siso != value))
				{
					this.OnsisoChanging(value);
					this.SendPropertyChanging();
					this._siso = value;
					this.SendPropertyChanged("siso");
					this.OnsisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lop_tbl_sinhvien", Storage="_tbl_sinhviens", ThisKey="malop", OtherKey="malop")]
		public EntitySet<tbl_sinhvien> tbl_sinhviens
		{
			get
			{
				return this._tbl_sinhviens;
			}
			set
			{
				this._tbl_sinhviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_sinhviens(tbl_sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_lop = this;
		}
		
		private void detach_tbl_sinhviens(tbl_sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_lop = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_sinhvien")]
	public partial class tbl_sinhvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _hoten;
		
		private string _gioitinh;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _malop;
		
		private EntityRef<tbl_lop> _tbl_lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OnmalopChanging(string value);
    partial void OnmalopChanged();
    #endregion
		
		public tbl_sinhvien()
		{
			this._tbl_lop = default(EntityRef<tbl_lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NChar(10)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malop", DbType="NChar(10)")]
		public string malop
		{
			get
			{
				return this._malop;
			}
			set
			{
				if ((this._malop != value))
				{
					if (this._tbl_lop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmalopChanging(value);
					this.SendPropertyChanging();
					this._malop = value;
					this.SendPropertyChanged("malop");
					this.OnmalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lop_tbl_sinhvien", Storage="_tbl_lop", ThisKey="malop", OtherKey="malop", IsForeignKey=true)]
		public tbl_lop tbl_lop
		{
			get
			{
				return this._tbl_lop.Entity;
			}
			set
			{
				tbl_lop previousValue = this._tbl_lop.Entity;
				if (((previousValue != value) 
							|| (this._tbl_lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_lop.Entity = null;
						previousValue.tbl_sinhviens.Remove(this);
					}
					this._tbl_lop.Entity = value;
					if ((value != null))
					{
						value.tbl_sinhviens.Add(this);
						this._malop = value.malop;
					}
					else
					{
						this._malop = default(string);
					}
					this.SendPropertyChanged("tbl_lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_taikhoan")]
	public partial class tbl_taikhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ma_tk;
		
		private string _ten_dang_nhap;
		
		private string _mat_khau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_tkChanging(string value);
    partial void Onma_tkChanged();
    partial void Onten_dang_nhapChanging(string value);
    partial void Onten_dang_nhapChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    #endregion
		
		public tbl_taikhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tk", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma_tk
		{
			get
			{
				return this._ma_tk;
			}
			set
			{
				if ((this._ma_tk != value))
				{
					this.Onma_tkChanging(value);
					this.SendPropertyChanging();
					this._ma_tk = value;
					this.SendPropertyChanged("ma_tk");
					this.Onma_tkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dang_nhap", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ten_dang_nhap
		{
			get
			{
				return this._ten_dang_nhap;
			}
			set
			{
				if ((this._ten_dang_nhap != value))
				{
					this.Onten_dang_nhapChanging(value);
					this.SendPropertyChanging();
					this._ten_dang_nhap = value;
					this.SendPropertyChanged("ten_dang_nhap");
					this.Onten_dang_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
